#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DETECTION_BACKEND="${DETECTION_BACKEND:-gazebo_color}"

case "$DETECTION_BACKEND" in
  gazebo_color)
    USE_MOCK_YOLO_VALUE=false
    USE_GAZEBO_COLOR_DETECTOR_VALUE=true
    USE_REAL_YOLO_VALUE=false
    ;;
  yolo)
    USE_MOCK_YOLO_VALUE=false
    USE_GAZEBO_COLOR_DETECTOR_VALUE=false
    USE_REAL_YOLO_VALUE=true
    ;;
  mock)
    USE_MOCK_YOLO_VALUE=true
    USE_GAZEBO_COLOR_DETECTOR_VALUE=false
    USE_REAL_YOLO_VALUE=false
    ;;
  *)
    echo "unsupported DETECTION_BACKEND=$DETECTION_BACKEND; expected gazebo_color, yolo, or mock" >&2
    exit 2
    ;;
esac

exec env \
  DETECTION_BACKEND="$DETECTION_BACKEND" \
  USE_GZCLIENT=false \
  USE_RVIZ=false \
  USE_MOCK_YOLO="$USE_MOCK_YOLO_VALUE" \
  USE_GAZEBO_COLOR_DETECTOR="$USE_GAZEBO_COLOR_DETECTOR_VALUE" \
  USE_REAL_YOLO="$USE_REAL_YOLO_VALUE" \
  USE_VISION_TARGET_PROJECTION=true \
  USE_VISION_OVERLAY="${USE_VISION_OVERLAY:-true}" \
  USE_VISION_EPISODE_RECORDER="${USE_VISION_EPISODE_RECORDER:-false}" \
  CAMERA_IMAGE_TOPIC="${CAMERA_IMAGE_TOPIC:-/camera/color/image_raw}" \
  DETECTIONS_TOPIC="${DETECTIONS_TOPIC:-/detections}" \
  VISION_TARGETS_TOPIC="${VISION_TARGETS_TOPIC:-/vision/targets}" \
  VISION_OVERLAY_TOPIC="${VISION_OVERLAY_TOPIC:-/vision/debug/image_overlay}" \
  VISION_EPISODE_ID="${VISION_EPISODE_ID:-sim_vision_smoke_$(date +%Y%m%d_%H%M%S)}" \
  VISION_EPISODE_OUTPUT_DIR="${VISION_EPISODE_OUTPUT_DIR:-docs/generated/vision-episodes}" \
  VISION_SNAPSHOT_REQUIRED_STREAMS="${VISION_SNAPSHOT_REQUIRED_STREAMS:-detections,vision_targets,joint_states}" \
  VISION_SNAPSHOT_MAX_STREAM_AGE_SEC="${VISION_SNAPSHOT_MAX_STREAM_AGE_SEC:-0.75}" \
  VISION_IMAGE_SNAPSHOT_EVERY_N="${VISION_IMAGE_SNAPSHOT_EVERY_N:-30}" \
  VISION_MAX_IMAGE_SNAPSHOTS="${VISION_MAX_IMAGE_SNAPSHOTS:-20}" \
  STATUS_HEARTBEAT_ENABLED="${STATUS_HEARTBEAT_ENABLED:-true}" \
  STATUS_HEARTBEAT_PERIOD_SEC="${STATUS_HEARTBEAT_PERIOD_SEC:-1.0}" \
  BENCHMARK_REACH_ENABLED="${BENCHMARK_REACH_ENABLED:-false}" \
  BENCHMARK_PREFERRED_CATEGORY="${BENCHMARK_PREFERRED_CATEGORY:-auto}" \
  BENCHMARK_TRIGGER_COOLDOWN_SEC="${BENCHMARK_TRIGGER_COOLDOWN_SEC:-8.0}" \
  BENCHMARK_REPORT_DIR="${BENCHMARK_REPORT_DIR:-docs/generated/vision-episodes}" \
  BENCHMARK_REACH_THRESHOLD_M="${BENCHMARK_REACH_THRESHOLD_M:-0.08}" \
  YOLO_MODEL_PATH="${YOLO_MODEL_PATH:-yolov8n.pt}" \
  YOLO_DEVICE="${YOLO_DEVICE:-cpu}" \
  ENABLE_ROSBRIDGE=false \
  START_BACKEND=false \
  START_FRONTEND=false \
  bash "$ROOT_DIR/tools/e2e/start_visible_demo_stack.sh"
